<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EHub.Application\EHub.Application.csproj" />
    <ProjectReference Include="..\EHub.Infrastructure\EHub.Infrastructure.csproj" />
    <ProjectReference Include="..\EHub.Contracts\EHub.Contracts.csproj" />
    <ProjectReference Include="..\EHub.Shared\EHub.Shared.csproj" />
  </ItemGroup>

</Project>
