import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { Clock3, FileText, History, MessageSquare, MoreHorizontal, Send, Trash2, Upload, X } from 'lucide-react';
import { productFeedbackApi } from '../../api/productFeedbackApi';
import { unwrapApiData } from '../../utils/classMappers';

export default function FeedbackPage({ admin = false }: { admin?: boolean }) {
  const [items, setItems] = useState<any[]>([]); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [files, setFiles] = useState<File[]>([]); const [sending, setSending] = useState(false); const [showHistory, setShowHistory] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [sentDate, setSentDate] = useState('');
  const load = async () => { try { const all: any[] = unwrapApiData(await (admin ? productFeedbackApi.inbox({}) : productFeedbackApi.mine())) || []; setItems(Array.from(new Map(all.map(item => [`${admin ? item.reporterEmail : ''}\u0000${item.title}\u0000${item.description}`, item])).values())); } catch { toast.error('Unable to load feedback.'); } };
  useEffect(() => { load(); }, []);
  const selectFiles = (input: FileList | null) => setFiles(Array.from(input || []).slice(0, 3));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (sending) return; setSending(true); try { const created: any = unwrapApiData(await productFeedbackApi.create({ title, description, contextUrl: location.pathname, category: 'Other', priority: 'Medium' })); for (const file of files) await productFeedbackApi.upload(created.id, file); toast.success('Cảm ơn bạn. Góp ý của bạn đã được ghi nhận.'); setTitle(''); setDescription(''); setFiles([]); load(); } catch { toast.error('Unable to send feedback.'); } finally { setSending(false); } };
  const removeOne = async (id: string) => { if (!window.confirm('Delete this feedback permanently?')) return; try { await productFeedbackApi.remove(id); setItems(current => current.filter(item => item.id !== id)); toast.success('Feedback deleted.'); } catch { toast.error('Unable to delete feedback.'); } };
  const removeAll = async () => { if (!items.length || !window.confirm(`Delete all ${items.length} feedback items permanently?`)) return; try { await productFeedbackApi.removeAll(); setItems([]); toast.success('All feedback deleted.'); } catch { toast.error('Unable to delete feedback.'); } };
  const visibleItems = items.filter(item => { const text = `${item.title} ${item.description} ${item.reporterName || ''} ${item.reporterEmail || ''}`.toLowerCase(); return (!search || text.includes(search.toLowerCase())) && (!role || item.reporterRole === role) && (!sentDate || new Date(item.createdAtUtc).toISOString().slice(0, 10) === sentDate); });
  const history = <div className="space-y-3">{visibleItems.length ? visibleItems.map(item => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-primary-50 text-primary dark:bg-primary/15"><MessageSquare className="h-4 w-4" /></span><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{item.title}</h3>{admin && <p className="mt-1 text-xs text-slate-500">{item.reporterName} · {item.reporterRole}</p>}<p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Clock3 className="h-3.5 w-3.5" />{new Date(item.createdAtUtc).toLocaleString()}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.description}</p></div>{admin && <button type="button" onClick={() => removeOne(item.id)} className="rounded-lg p-2 text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30" aria-label="Delete feedback" title="Delete feedback"><Trash2 className="h-4 w-4" /></button>}</div></article>) : <div className="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">{admin ? 'No feedback matches these filters.' : 'No feedback sent yet.'}</div>}</div>;
  const form = <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-800 sm:p-7"><div className="mb-6"><h2 className="font-bold">Share your feedback</h2><p className="mt-1 text-sm text-slate-500">Tell us what is working well or what could be improved.</p></div><div className="space-y-5"><label className="block text-sm font-semibold">Subject<input required minLength={5} maxLength={150} value={title} onChange={e => setTitle(e.target.value)} placeholder="Summarize your feedback" className="mt-2 w-full rounded-xl border border-slate-300 bg-transparent p-3 outline-none focus:border-primary dark:border-slate-600" /></label><label className="block text-sm font-semibold">Details<textarea required minLength={20} maxLength={3000} value={description} onChange={e => setDescription(e.target.value)} placeholder="Describe what happened and what would make the experience better." className="mt-2 min-h-40 w-full resize-y rounded-xl border border-slate-300 bg-transparent p-3 outline-none focus:border-primary dark:border-slate-600" /></label><label onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); selectFiles(e.dataTransfer.files); }} className="flex cursor-pointer flex-col items-center rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center hover:border-primary hover:bg-primary-50 dark:border-slate-600 dark:bg-slate-900/30"><Upload className="h-5 w-5 text-primary" /><span className="mt-3 text-sm font-semibold">Attach supporting files</span><span className="mt-1 text-xs text-slate-500">Drop files here or click to browse · up to 3 files, 10 MB each</span><input className="sr-only" type="file" multiple accept=".png,.jpg,.jpeg,.webp,.pdf,.docx,.pptx" onChange={e => selectFiles(e.target.files)} /></label>{files.map(file => <p key={`${file.name}-${file.lastModified}`} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm dark:bg-slate-900"><FileText className="h-4 w-4 text-primary" />{file.name}</p>)}<button disabled={sending} className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4" />{sending ? 'Sending…' : 'Send feedback'}</button></div></form>;
  const filters = <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800 md:grid-cols-2 xl:grid-cols-4"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search feedback or sender" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-primary dark:border-slate-600 xl:col-span-4" /><select value={role} onChange={e => setRole(e.target.value)} className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-primary dark:border-slate-600"><option value="">All roles</option><option>Student</option><option>Lecturer</option><option>Mentor</option></select><input value={sentDate} onChange={e => setSentDate(e.target.value)} type="date" aria-label="Sent date" className="rounded-xl border border-slate-300 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-primary dark:border-slate-600" /><button type="button" onClick={() => { setSearch(''); setRole(''); setSentDate(''); }} className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold text-primary hover:bg-primary-50 dark:border-slate-600">Clear filters</button><button type="button" onClick={removeAll} disabled={!items.length} className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-3 py-2.5 text-sm font-semibold text-white hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50"><Trash2 className="h-4 w-4" />Delete all</button></div>;
  return <main className="mx-auto max-w-7xl p-6 sm:p-8"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">E-HUB SUPPORT</p><h1 className="mt-1 text-3xl font-bold">{admin ? 'Feedback Inbox' : 'Send feedback'}</h1></div>{admin ? <button type="button" onClick={() => setFiltersOpen(value => !value)} className={`inline-flex h-11 w-11 items-center justify-center rounded-xl border text-primary ${filtersOpen ? 'border-primary bg-primary-50' : 'border-slate-300 hover:bg-slate-50 dark:border-slate-600 dark:hover:bg-slate-800'}`} aria-label="Toggle filters" title="Filters"><MoreHorizontal className="h-5 w-5" /></button> : <button type="button" onClick={() => setShowHistory(value => !value)} className={`inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${showHistory ? 'bg-primary text-white' : 'border border-primary text-primary hover:bg-primary-50'}`}><History className="h-4 w-4" />{showHistory ? 'Hide sent feedback' : 'View sent feedback'}</button>}</header>{admin ? <section className="space-y-6">{filtersOpen && filters}<p className="text-sm text-slate-500">Showing {visibleItems.length} of {items.length} feedback items</p>{history}</section> : <div className={showHistory ? 'grid items-start gap-8 lg:grid-cols-[minmax(0,1.7fr)_minmax(320px,1fr)]' : 'w-full'}><div>{form}</div>{showHistory && <aside className="rounded-2xl border border-slate-200 bg-slate-50/80 p-5 dark:border-slate-700 dark:bg-slate-900/30"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Your feedback</h2><p className="mt-1 text-xs text-slate-500">{items.length} item{items.length === 1 ? '' : 's'} submitted</p></div><button onClick={() => setShowHistory(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-200" aria-label="Hide sent feedback"><X className="h-4 w-4" /></button></div>{history}</aside>}</div>}</main>;
}
