<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EHub.Contracts\EHub.Contracts.csproj" />
    <ProjectReference Include="..\..\src\EHub.Domain\EHub.Domain.csproj" />
    <ProjectReference Include="..\..\src\EHub.Infrastructure\EHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
